from Infernux.components.component import InxComponent
from Infernux.core.asset_ref import ParticleGraphRef
from Infernux.particle import ExecutionTarget, ParticleRuntimeCompatibility

class ParticleSystem(InxComponent):
    graph: ParticleGraphRef
    simulation_speed: float
    play_on_awake: bool
    def play(self, emitter_index: int | None = None) -> bool: ...
    def pause(self, emitter_index: int | None = None) -> bool: ...
    def stop(self, emitter_index: int | None = None) -> bool: ...
    def restart(self, emitter_index: int | None = None, *, honor_play_on_start: bool = False) -> bool: ...
    def start_emitter(self, emitter_index: int) -> bool: ...
    def pause_emitter(self, emitter_index: int) -> bool: ...
    def terminate_emitter(self, emitter_index: int) -> bool: ...
    def emitter_runtime_target(self, emitter_index: int) -> ExecutionTarget | None: ...
    def emitter_reload_compatibility(self, emitter_index: int) -> ParticleRuntimeCompatibility | None: ...
    def editor_preview_begin(self) -> bool: ...
    def editor_preview_update(self, delta_time: float, speed: float = 1.0) -> bool: ...
    def editor_preview_play(self) -> bool: ...
    def editor_preview_pause(self) -> bool: ...
    def editor_preview_stop(self) -> bool: ...
    def editor_preview_set_emitter_muted(self, emitter_index: int, muted: bool) -> bool: ...
    def editor_preview_set_emitter_solo(self, emitter_index: int, solo: bool) -> bool: ...
    def editor_preview_restart_emitter(self, emitter_index: int) -> bool: ...
    def editor_preview_emitter_states(self) -> list[dict]: ...
    def editor_preview_end(self) -> None: ...
