from Infernux.components.component import InxComponent
from Infernux.core.asset_ref import ParticleGraphRef
from Infernux.particle import ExecutionTarget, ParticleRuntimeCompatibility

class ParticleSystem(InxComponent):
    graph: ParticleGraphRef
    simulation_target: ExecutionTarget
    simulation_speed: float
    play_on_awake: bool
    def play(self, emitter_index: int | None = None) -> bool: ...
    def pause(self, emitter_index: int | None = None) -> bool: ...
    def stop(self, emitter_index: int | None = None) -> bool: ...
    def restart(self, emitter_index: int | None = None) -> bool: ...
    def start_emitter(self, emitter_index: int) -> bool: ...
    def pause_emitter(self, emitter_index: int) -> bool: ...
    def terminate_emitter(self, emitter_index: int) -> bool: ...
    def emitter_runtime_target(self, emitter_index: int) -> ExecutionTarget | None: ...
    def emitter_reload_compatibility(self, emitter_index: int) -> ParticleRuntimeCompatibility | None: ...
