from typing import Callable, Optional

class InputContext:
    context_id: str
    owner_id: str
    priority: int
    blocks_lower: bool
    def __init__(self, context_id: str, owner_id: str, priority: int = 0, blocks_lower: bool = False) -> None: ...

class InputContextStack:
    def __init__(self) -> None: ...
    def push(self, context: InputContext) -> None: ...
    def remove(self, context_id: str) -> None: ...
    def remove_owner(self, owner_id: str) -> None: ...
    def ordered(self) -> tuple[InputContext, ...]: ...

class FocusSnapshot:
    active_panel_id: str
    active_view_id: str
    active_document_id: str
    child_context_id: str
    capture_owner_id: str
    def __init__(self, active_panel_id: str = "", active_view_id: str = "", active_document_id: str = "", child_context_id: str = "", capture_owner_id: str = "") -> None: ...

class FocusService:
    input_contexts: InputContextStack
    def __init__(self) -> None: ...
    @classmethod
    def instance(cls) -> FocusService: ...
    @property
    def snapshot(self) -> FocusSnapshot: ...
    @property
    def revision(self) -> int: ...
    @property
    def pending_panel_id(self) -> str: ...
    def add_listener(self, callback: Callable[[FocusSnapshot], None]) -> None: ...
    def remove_listener(self, callback: Callable[[FocusSnapshot], None]) -> None: ...
    def request_panel_focus(self, panel_id: str) -> bool: ...
    def consume_panel_focus_request(self, panel_id: str) -> bool: ...
    def activate_panel(self, panel_id: str, *, view_id: Optional[str] = None, document_id: Optional[str] = None, child_context_id: Optional[str] = None) -> bool: ...
    def deactivate_panel(self, panel_id: str) -> bool: ...
    def set_child_context(self, panel_id: str, context_id: str) -> bool: ...
    def set_capture_owner(self, owner_id: str) -> bool: ...
