from enum import Enum, IntFlag
from typing import Any, Optional, Protocol

class DocumentKind(str, Enum):
    SCENE: DocumentKind
    PREFAB: DocumentKind
    MATERIAL: DocumentKind
    RENDER_EFFECT: DocumentKind
    ANIMATION_CLIP: DocumentKind
    ANIMATION_FSM: DocumentKind
    TIMELINE: DocumentKind
    PARTICLE_GRAPH: DocumentKind
    UI_DOCUMENT: DocumentKind
    GENERIC: DocumentKind

class DocumentIdentityKind(str, Enum):
    ASSET_GUID: DocumentIdentityKind
    RESOURCE_PATH: DocumentIdentityKind
    SESSION: DocumentIdentityKind

class DocumentKey:
    kind: DocumentKind
    identity_kind: DocumentIdentityKind
    identity: str
    def __init__(self, kind: DocumentKind, identity_kind: DocumentIdentityKind, identity: str) -> None: ...
    @classmethod
    def asset(cls, kind: DocumentKind, guid: str) -> DocumentKey: ...
    @classmethod
    def resource(cls, kind: DocumentKind, path: str) -> DocumentKey: ...
    @classmethod
    def session(cls, kind: DocumentKind, session_id: str = "") -> DocumentKey: ...

class DocumentState(str, Enum):
    READY: DocumentState
    SAVING: DocumentState
    CONFLICT: DocumentState
    CLOSED: DocumentState

class DocumentCapability(IntFlag):
    NONE: DocumentCapability
    SAVE: DocumentCapability
    SAVE_AS: DocumentCapability
    DISCARD: DocumentCapability

class DocumentActionStatus(str, Enum):
    APPLIED: DocumentActionStatus
    PENDING: DocumentActionStatus
    NO_OP: DocumentActionStatus
    REJECTED: DocumentActionStatus
    FAILED: DocumentActionStatus

class SaveTicketStatus(str, Enum):
    PENDING: SaveTicketStatus
    SUCCEEDED: SaveTicketStatus
    FAILED: SaveTicketStatus
    CANCELLED: SaveTicketStatus

class DocumentActionResult:
    status: DocumentActionStatus
    message: str
    def __init__(self, status: DocumentActionStatus, message: str = "") -> None: ...
    @property
    def accepted(self) -> bool: ...

class SaveTicket:
    ticket_id: str
    document_id: str
    captured_revision: int
    save_as: bool
    operation_id: str
    status: SaveTicketStatus
    message: str
    @property
    def is_pending(self) -> bool: ...

class DocumentController(Protocol):
    def save(self, *, ticket: SaveTicket, save_as: bool = False) -> Any: ...
    def discard(self, *, document_id: str) -> Any: ...

class EditorDocument:
    document_id: str
    key: DocumentKey
    kind: DocumentKind
    title: str
    resource_path: str
    revision: int
    saved_revision: int
    state: DocumentState
    capabilities: DocumentCapability
    view_ids: set[str]
    controller: Optional[DocumentController]
    @property
    def is_dirty(self) -> bool: ...

class DocumentRegistry:
    def __init__(self) -> None: ...
    @classmethod
    def instance(cls) -> DocumentRegistry: ...
    @property
    def revision(self) -> int: ...
    @property
    def documents(self) -> tuple[EditorDocument, ...]: ...
    def create(self, kind: DocumentKind, title: str, *, document_id: str = "", key: Optional[DocumentKey] = None, resource_path: str = "", revision: int = 0, saved_revision: Optional[int] = None, capabilities: DocumentCapability = DocumentCapability.NONE, controller: Optional[DocumentController] = None) -> EditorDocument: ...
    def get(self, document_id: str) -> Optional[EditorDocument]: ...
    def require(self, document_id: str) -> EditorDocument: ...
    def get_by_key(self, key: DocumentKey) -> Optional[EditorDocument]: ...
    def open_or_create(self, key: DocumentKey, title: str, *, resource_path: str = "", revision: int = 0, saved_revision: Optional[int] = None, capabilities: DocumentCapability = DocumentCapability.NONE, controller: Optional[DocumentController] = None) -> tuple[EditorDocument, bool]: ...
    def rekey(self, document_id: str, key: DocumentKey, *, resource_path: Optional[str] = None) -> bool: ...
    def document_for_view(self, view_id: str) -> Optional[EditorDocument]: ...
    def attach_view(self, document_id: str, view_id: str) -> bool: ...
    def detach_view(self, view_id: str) -> Optional[str]: ...
    def unregister(self, document_id: str) -> bool: ...
    def update_metadata(self, document_id: str, *, title: Optional[str] = None, resource_path: Optional[str] = None, capabilities: Optional[DocumentCapability] = None, controller: Optional[DocumentController] = None) -> bool: ...
    def mark_changed(self, document_id: str) -> int: ...
    def reserve_content_revision(self, document_id: str) -> int: ...
    def mark_saved(self, document_id: str, revision: Optional[int] = None) -> int: ...
    def restore_content_revision(self, document_id: str, revision: int) -> int: ...
    def mark_conflict(self, document_id: str) -> None: ...
    def restore_revision_state(self, document_id: str, *, revision: int, saved_revision: int, state: DocumentState = DocumentState.READY) -> None: ...
    def dirty_documents(self) -> tuple[EditorDocument, ...]: ...
    def request_save(self, document_id: str, *, save_as: bool = False) -> DocumentActionResult: ...
    def begin_save(self, document_id: str, *, save_as: bool = False) -> SaveTicket: ...
    def active_save_ticket(self, document_id: str) -> Optional[SaveTicket]: ...
    def get_save_ticket(self, ticket_id: str) -> Optional[SaveTicket]: ...
    def complete_save(self, ticket_id: str, *, success: bool, cancelled: bool = False, key: Optional[DocumentKey] = None, resource_path: Optional[str] = None, title: Optional[str] = None, message: str = "") -> SaveTicket: ...
    def request_discard(self, document_id: str) -> DocumentActionResult: ...
    def is_save_pending(self, document_id: str) -> bool: ...
    def clear(self) -> None: ...
