from enum import Enum, IntFlag
from typing import Any, Optional, Protocol

class DocumentKind(str, Enum):
    SCENE: DocumentKind
    PREFAB: DocumentKind
    MATERIAL: DocumentKind
    RENDER_EFFECT: DocumentKind
    ANIMATION_CLIP: DocumentKind
    ANIMATION_FSM: DocumentKind
    TIMELINE: DocumentKind
    PARTICLE_GRAPH: DocumentKind
    UI_DOCUMENT: DocumentKind
    GENERIC: DocumentKind

class DocumentState(str, Enum):
    READY: DocumentState
    SAVING: DocumentState
    CONFLICT: DocumentState
    CLOSED: DocumentState

class DocumentCapability(IntFlag):
    NONE: DocumentCapability
    SAVE: DocumentCapability
    SAVE_AS: DocumentCapability
    DISCARD: DocumentCapability

class DocumentActionStatus(str, Enum):
    APPLIED: DocumentActionStatus
    PENDING: DocumentActionStatus
    NO_OP: DocumentActionStatus
    REJECTED: DocumentActionStatus
    FAILED: DocumentActionStatus

class DocumentActionResult:
    status: DocumentActionStatus
    message: str
    def __init__(self, status: DocumentActionStatus, message: str = "") -> None: ...
    @property
    def accepted(self) -> bool: ...

class DocumentController(Protocol):
    def save(self, *, save_as: bool = False) -> Any: ...
    def discard(self) -> Any: ...
    def is_save_pending(self) -> bool: ...

class EditorDocument:
    document_id: str
    kind: DocumentKind
    title: str
    resource_path: str
    revision: int
    saved_revision: int
    state: DocumentState
    capabilities: DocumentCapability
    view_ids: set[str]
    controller: Optional[DocumentController]
    @property
    def is_dirty(self) -> bool: ...

class DocumentRegistry:
    def __init__(self) -> None: ...
    @classmethod
    def instance(cls) -> DocumentRegistry: ...
    @property
    def revision(self) -> int: ...
    @property
    def documents(self) -> tuple[EditorDocument, ...]: ...
    def create(self, kind: DocumentKind, title: str, *, document_id: str = "", resource_path: str = "", revision: int = 0, saved_revision: Optional[int] = None, capabilities: DocumentCapability = DocumentCapability.NONE, controller: Optional[DocumentController] = None) -> EditorDocument: ...
    def get(self, document_id: str) -> Optional[EditorDocument]: ...
    def require(self, document_id: str) -> EditorDocument: ...
    def document_for_view(self, view_id: str) -> Optional[EditorDocument]: ...
    def attach_view(self, document_id: str, view_id: str) -> bool: ...
    def detach_view(self, view_id: str) -> Optional[str]: ...
    def unregister(self, document_id: str) -> bool: ...
    def update_metadata(self, document_id: str, *, title: Optional[str] = None, resource_path: Optional[str] = None, capabilities: Optional[DocumentCapability] = None, controller: Optional[DocumentController] = None) -> bool: ...
    def mark_changed(self, document_id: str) -> int: ...
    def mark_saved(self, document_id: str, revision: Optional[int] = None) -> int: ...
    def mark_conflict(self, document_id: str) -> None: ...
    def dirty_documents(self) -> tuple[EditorDocument, ...]: ...
    def request_save(self, document_id: str, *, save_as: bool = False) -> DocumentActionResult: ...
    def request_discard(self, document_id: str) -> DocumentActionResult: ...
    def is_save_pending(self, document_id: str) -> bool: ...
    def clear(self) -> None: ...
