from dataclasses import dataclass
from typing import Callable, Optional
from .descriptors import SelectionDomain, SelectionTarget
from .selection import SelectionService

@dataclass(frozen=True)
class NavigationRequest:
    record_history: bool = ...
    activate_panel: bool = ...

NavigationAdapter = Callable[[SelectionTarget, NavigationRequest], bool]

class NavigationService:
    def __init__(self, selection: Optional[SelectionService] = ...) -> None: ...
    def register(self, domain: SelectionDomain, adapter: NavigationAdapter,
                 *, replace: bool = ...) -> None: ...
    def unregister(self, domain: SelectionDomain) -> bool: ...
    def locate(self, target: SelectionTarget, *, owner_id: str,
               reason: str = ..., record_history: bool = ...,
               activate_panel: bool = ...) -> bool: ...
    def reveal(self, target: SelectionTarget, *, record_history: bool = ...,
               activate_panel: bool = ...) -> bool: ...
    def clear(self) -> None: ...
