from typing import Callable, Iterable, Sequence
from .descriptors import SelectionSnapshot, SelectionTarget

class SelectionChange:
    before: SelectionSnapshot
    after: SelectionSnapshot
    reason: str
    record_history: bool

class SelectionService:
    def __init__(self) -> None: ...
    @classmethod
    def instance(cls) -> SelectionService: ...
    @classmethod
    def install(cls, service: SelectionService) -> None: ...
    @property
    def snapshot(self) -> SelectionSnapshot: ...
    @property
    def revision(self) -> int: ...
    def add_listener(self, callback: Callable[[SelectionChange], None]) -> None: ...
    def remove_listener(self, callback: Callable[[SelectionChange], None]) -> None: ...
    def set_ordered_targets(self, owner_id: str, targets: Sequence[SelectionTarget]) -> None: ...
    def replace(self, targets: Iterable[SelectionTarget], *, owner_id: str, primary: SelectionTarget | None = None, anchor: SelectionTarget | None = None, reason: str = "replace", record_history: bool = True) -> bool: ...
    def select(self, target: SelectionTarget, *, owner_id: str, reason: str = "select", record_history: bool = True) -> bool: ...
    def toggle(self, target: SelectionTarget, *, owner_id: str, reason: str = "toggle", record_history: bool = True) -> bool: ...
    def range_select(self, target: SelectionTarget, *, owner_id: str, reason: str = "range_select", record_history: bool = True) -> bool: ...
    def clear(self, *, reason: str = "clear", record_history: bool = True) -> bool: ...
    def apply_snapshot(self, snapshot: SelectionSnapshot, *, reason: str = "restore", record_history: bool = False) -> bool: ...
