from typing import Any

class Application:
    @staticmethod
    def is_editor() -> bool: ...
    @staticmethod
    def is_player() -> bool: ...
    @staticmethod
    def data_path() -> str: ...
    @staticmethod
    def renderer_state() -> dict[str, Any]: ...
    @staticmethod
    def quit(exit_code: int = 0) -> bool: ...
