from __future__ import annotations

from typing import Any, Iterable, Mapping, Optional

RUNTIME_PHASE_NAMES: tuple[str, str, str]

class RuntimeMethodDescriptor:
    name: str
    raw: Any
    kind: str
    signature: str
    @property
    def bind_instance(self) -> bool: ...
    def invoke(self, instance: Any, *args: Any) -> Any: ...
    def bind(self, instance: Any) -> Any: ...

class RuntimeTypeDispatchDescriptor:
    component_type: type
    epoch_id: int
    phase_methods: tuple[Optional[RuntimeMethodDescriptor], ...]
    methods: Mapping[str, RuntimeMethodDescriptor]
    @property
    def phase_dispatch(self) -> tuple[tuple[Any, bool], ...]: ...
    @property
    def phase_presence(self) -> tuple[bool, bool, bool]: ...
    @property
    def phase_invokers(self) -> tuple[Any, ...]: ...
    def has_phase(self, phase: str) -> bool: ...
    def resolve_method(self, instance: Any, name: str) -> Any: ...

class RuntimeRevisionEpoch:
    epoch_id: int
    descriptors: Mapping[type, RuntimeTypeDispatchDescriptor]
    def descriptor_for(self, component_type: type) -> Optional[RuntimeTypeDispatchDescriptor]: ...
    def has_phase(self, component_type: type, phase: str) -> bool: ...
    def resolve_method(self, instance: Any, name: str) -> Any: ...

class RuntimeOwnerIdentity:
    component_id: int
    native_generation: int

class CallbackResolution:
    status: str
    callback: Optional[Any]
    message: str
    resolved: bool

class CallbackInvocation:
    reference: ReloadableCallbackRef
    status: str
    message: str

class ReloadableCallbackRef:
    owner_ref: Optional[Any]
    owner_identity: Optional[RuntimeOwnerIdentity]
    owner_type: Optional[type]
    method_name: str
    expected_signature: str
    registration_epoch: int
    legacy_callable: Optional[Any]
    pinned_revision: Optional[int]
    fallback_descriptor: Optional[RuntimeTypeDispatchDescriptor]
    is_legacy: bool
    @classmethod
    def normalize(cls, callback: Any, *, expected_signature: Optional[str] = ..., epoch: Optional[RuntimeRevisionEpoch] = ...) -> ReloadableCallbackRef: ...
    def resolve(self, epoch: Optional[RuntimeRevisionEpoch] = ...) -> CallbackResolution: ...
    def invoke(self, *args: Any, epoch: Optional[RuntimeRevisionEpoch] = ..., propagate_exceptions: bool = ...) -> CallbackInvocation: ...
    def matches(self, callback: Any) -> bool: ...
    def matches_owner_method(self, owner: Any, method_name: str) -> bool: ...

class ReloadableCallbackRegistry:
    def __init__(self) -> None: ...
    def add_listener(self, callback: Any, *, expected_signature: Optional[str] = ...) -> ReloadableCallbackRef: ...
    def remove_listener(self, callback: Any) -> None: ...
    def remove_all_listeners(self) -> None: ...
    def invoke(self, *args: Any, epoch: Optional[RuntimeRevisionEpoch] = ..., propagate_exceptions: bool = ...) -> tuple[CallbackInvocation, ...]: ...
    @property
    def listener_count(self) -> int: ...
    def validate_epoch(self, epoch: RuntimeRevisionEpoch, component_types: Iterable[type]) -> None: ...

class RuntimeDispatchPublication:
    before: RuntimeRevisionEpoch
    after: RuntimeRevisionEpoch
    committed: bool
    rolled_back: bool
    def commit(self) -> None: ...
    def rollback(self) -> None: ...

def current_runtime_epoch() -> RuntimeRevisionEpoch: ...
def assert_runtime_dispatch_safe_point() -> None: ...
def build_type_dispatch_descriptor(component_type: type, *, epoch_id: int = 0) -> RuntimeTypeDispatchDescriptor: ...
def ensure_runtime_compatibility_mirror(component_type: type) -> RuntimeTypeDispatchDescriptor: ...
def ensure_runtime_dispatch_types(component_types: Iterable[type]) -> RuntimeRevisionEpoch: ...
def publish_runtime_dispatch_epoch(
    component_types: Iterable[type],
    instances_by_type: Optional[Mapping[type, Iterable[Any]]] = None,
    *,
    sync_compatibility: bool = True,
    retired_types: Iterable[type] = ...,
    defer_commit: bool = False,
) -> RuntimeDispatchPublication: ...
def resolve_runtime_method(instance: Any, name: str, *, epoch: Optional[RuntimeRevisionEpoch] = None) -> Any: ...
def has_runtime_phase(component_type: type, phase: str) -> bool: ...
def runtime_descriptor_diagnostic(component_type: type) -> dict[str, Any]: ...
def validate_runtime_callback_bindings(epoch: RuntimeRevisionEpoch, component_types: Iterable[type]) -> None: ...
