#!/usr/bin/env python3
"""Generate a 1000x1000 vertex water plane as FBX ASCII 7.4."""

from __future__ import annotations

import subprocess
import sys
import time
from pathlib import Path

import numpy as np

GRID_N = 1000  # vertices per side
PLANE_SIZE = 100.0  # world units (XZ)


def desktop_path() -> Path:
    try:
        import ctypes
        from ctypes import wintypes

        CSIDL_DESKTOP = 0
        SHGFP_TYPE_CURRENT = 0
        buf = ctypes.create_unicode_buffer(wintypes.MAX_PATH)
        hr = ctypes.windll.shell32.SHGetFolderPathW(
            None, CSIDL_DESKTOP, None, SHGFP_TYPE_CURRENT, buf
        )
        if hr == 0 and buf.value:
            return Path(buf.value)
    except Exception:
        pass
    out = subprocess.check_output(
        [
            "powershell",
            "-NoProfile",
            "-Command",
            "[Environment]::GetFolderPath('Desktop')",
        ],
        text=True,
        encoding="utf-8",
    ).strip()
    return Path(out)


def build_mesh(n: int, size: float):
    """Y-up plane on XZ, centered at origin, size x size."""
    xs = np.linspace(-size * 0.5, size * 0.5, n, dtype=np.float64)
    zs = np.linspace(-size * 0.5, size * 0.5, n, dtype=np.float64)
    xx, zz = np.meshgrid(xs, zs, indexing="xy")
    yy = np.zeros_like(xx)
    vertices = np.stack([xx.ravel(), yy.ravel(), zz.ravel()], axis=1)

    u = np.linspace(0.0, 1.0, n, dtype=np.float64)
    v = np.linspace(0.0, 1.0, n, dtype=np.float64)
    uu, vv = np.meshgrid(u, v, indexing="xy")
    uvs = np.stack([uu.ravel(), vv.ravel()], axis=1)

    quads_w = n - 1
    quads_h = n - 1
    i = np.repeat(np.arange(quads_h, dtype=np.int32), quads_w)
    j = np.tile(np.arange(quads_w, dtype=np.int32), quads_h)
    a = i * n + j
    b = a + 1
    c = a + n + 1
    d = a + n
    # Two triangles per quad; last index of each polygon is bitwise NOT
    # Tri1: a,b,~c  Tri2: a,c,~d
    tri_count = quads_w * quads_h * 2
    poly_indices = np.empty(tri_count * 3, dtype=np.int32)
    poly_indices[0::6] = a
    poly_indices[1::6] = b
    poly_indices[2::6] = np.bitwise_not(c)
    poly_indices[3::6] = a
    poly_indices[4::6] = c
    poly_indices[5::6] = np.bitwise_not(d)

    normals = np.zeros_like(vertices)
    normals[:, 1] = 1.0

    return vertices, poly_indices, normals, uvs, tri_count


def write_float_array(f, arr: np.ndarray, per_line: int = 24) -> None:
    flat = np.asarray(arr, dtype=np.float64).ravel()
    n = flat.size
    # Vectorized formatting in chunks for speed
    for start in range(0, n, per_line * 256):
        end = min(start + per_line * 256, n)
        block = flat[start:end]
        # Format with general precision; join with commas, insert newlines every per_line
        s = ",".join(np.char.mod("%.6g", block))
        # Insert newlines
        parts = s.split(",")
        lines = []
        for i in range(0, len(parts), per_line):
            lines.append(",".join(parts[i : i + per_line]))
        body = ",\n".join(lines)
        if end < n:
            f.write(body)
            f.write(",\n")
        else:
            f.write(body)
            f.write("\n")


def write_int_array(f, arr: np.ndarray, per_line: int = 32) -> None:
    flat = np.asarray(arr, dtype=np.int32).ravel()
    n = flat.size
    for start in range(0, n, per_line * 256):
        end = min(start + per_line * 256, n)
        block = flat[start:end]
        s = ",".join(map(str, block.tolist()))
        parts = s.split(",")
        lines = []
        for i in range(0, len(parts), per_line):
            lines.append(",".join(parts[i : i + per_line]))
        body = ",\n".join(lines)
        if end < n:
            f.write(body)
            f.write(",\n")
        else:
            f.write(body)
            f.write("\n")


def write_fbx_ascii(
    path: Path,
    vertices: np.ndarray,
    poly_indices: np.ndarray,
    normals: np.ndarray,
    uvs: np.ndarray,
) -> None:
    n_verts = int(vertices.shape[0])
    n_poly_idx = int(poly_indices.shape[0])
    geom_id = 1000001
    model_id = 1000002

    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write("; FBX 7.4.0 project file\n")
        f.write("; Generated by gen_water_plane_fbx.py — water surface plane\n")
        f.write("FBXHeaderExtension:  {\n")
        f.write("    FBXHeaderVersion: 1003\n")
        f.write("    FBXVersion: 7400\n")
        f.write('    Creator: "InfEngine gen_water_plane_fbx.py"\n')
        f.write("}\n")
        f.write("GlobalSettings:  {\n")
        f.write("    Version: 1000\n")
        f.write("    Properties70:  {\n")
        f.write('        P: "UpAxis", "int", "Integer", "",1\n')
        f.write('        P: "UpAxisSign", "int", "Integer", "",1\n')
        f.write('        P: "FrontAxis", "int", "Integer", "",2\n')
        f.write('        P: "FrontAxisSign", "int", "Integer", "",1\n')
        f.write('        P: "CoordAxis", "int", "Integer", "",0\n')
        f.write('        P: "CoordAxisSign", "int", "Integer", "",1\n')
        f.write('        P: "OriginalUpAxis", "int", "Integer", "",1\n')
        f.write('        P: "OriginalUpAxisSign", "int", "Integer", "",1\n')
        f.write('        P: "UnitScaleFactor", "double", "Number", "",1\n')
        f.write('        P: "OriginalUnitScaleFactor", "double", "Number", "",1\n')
        f.write("    }\n")
        f.write("}\n")
        f.write("Documents:  {\n")
        f.write("    Count: 1\n")
        f.write('    Document: 1000000, "Scene", "Scene" {\n')
        f.write("        Properties70:  {\n")
        f.write('            P: "SourceObject", "object", "", ""\n')
        f.write('            P: "ActiveAnimStackName", "KString", "", "", ""\n')
        f.write("        }\n")
        f.write("        RootNode: 0\n")
        f.write("    }\n")
        f.write("}\n")
        f.write("References:  {\n")
        f.write("}\n")
        f.write("Definitions:  {\n")
        f.write("    Version: 100\n")
        f.write("    Count: 3\n")
        f.write('    ObjectType: "GlobalSettings" {\n')
        f.write("        Count: 1\n")
        f.write("    }\n")
        f.write('    ObjectType: "Model" {\n')
        f.write("        Count: 1\n")
        f.write("    }\n")
        f.write('    ObjectType: "Geometry" {\n')
        f.write("        Count: 1\n")
        f.write("    }\n")
        f.write("}\n")
        f.write("Objects:  {\n")
        f.write(f'    Geometry: {geom_id}, "Geometry::WaterPlane", "Mesh" {{\n')
        f.write(f"        Vertices: *{n_verts * 3} {{\n")
        f.write("            a: ")
        write_float_array(f, vertices)
        f.write("        }\n")
        f.write(f"        PolygonVertexIndex: *{n_poly_idx} {{\n")
        f.write("            a: ")
        write_int_array(f, poly_indices)
        f.write("        }\n")
        f.write("        GeometryVersion: 124\n")
        f.write("        LayerElementNormal: 0 {\n")
        f.write("            Version: 101\n")
        f.write('            Name: ""\n')
        f.write('            MappingInformationType: "ByControlPoint"\n')
        f.write('            ReferenceInformationType: "Direct"\n')
        f.write(f"            Normals: *{n_verts * 3} {{\n")
        f.write("                a: ")
        write_float_array(f, normals)
        f.write("            }\n")
        f.write("        }\n")
        f.write("        LayerElementUV: 0 {\n")
        f.write("            Version: 101\n")
        f.write('            Name: "UVMap"\n')
        f.write('            MappingInformationType: "ByControlPoint"\n')
        f.write('            ReferenceInformationType: "Direct"\n')
        f.write(f"            UV: *{n_verts * 2} {{\n")
        f.write("                a: ")
        write_float_array(f, uvs)
        f.write("            }\n")
        f.write("        }\n")
        f.write("        Layer: 0 {\n")
        f.write("            Version: 100\n")
        f.write("            LayerElement:  {\n")
        f.write('                Type: "LayerElementNormal"\n')
        f.write("                TypedIndex: 0\n")
        f.write("            }\n")
        f.write("            LayerElement:  {\n")
        f.write('                Type: "LayerElementUV"\n')
        f.write("                TypedIndex: 0\n")
        f.write("            }\n")
        f.write("        }\n")
        f.write("    }\n")
        f.write(f'    Model: {model_id}, "Model::WaterPlane", "Mesh" {{\n')
        f.write("        Version: 232\n")
        f.write("        Properties70:  {\n")
        f.write('            P: "InheritanceType", "enum", "", "",1\n')
        f.write('            P: "DefaultAttributeIndex", "int", "Integer", "",0\n')
        f.write('            P: "Lcl Translation", "Lcl Translation", "", "A",0,0,0\n')
        f.write('            P: "Lcl Rotation", "Lcl Rotation", "", "A",0,0,0\n')
        f.write('            P: "Lcl Scaling", "Lcl Scaling", "", "A",1,1,1\n')
        f.write("        }\n")
        f.write("        Shading: Y\n")
        f.write('        Culling: "CullingOff"\n')
        f.write("    }\n")
        f.write("}\n")
        f.write("Connections:  {\n")
        f.write(f'    C: "OO",{model_id},0\n')
        f.write(f'    C: "OO",{geom_id},{model_id}\n')
        f.write("}\n")


def main() -> int:
    desk = desktop_path()
    out = desk / "WaterPlane_1M.fbx"
    print(f"Desktop: {desk}")
    print(f"Output:  {out}")
    print(f"Building {GRID_N}x{GRID_N} grid ({GRID_N * GRID_N} vertices)...")
    t0 = time.perf_counter()
    vertices, poly_indices, normals, uvs, tri_count = build_mesh(GRID_N, PLANE_SIZE)
    t1 = time.perf_counter()
    print(f"Mesh built in {t1 - t0:.2f}s — writing FBX ASCII...")
    write_fbx_ascii(out, vertices, poly_indices, normals, uvs)
    t2 = time.perf_counter()
    size = out.stat().st_size
    print(f"Done in {t2 - t0:.2f}s (write {t2 - t1:.2f}s)")
    print(f"path={out}")
    print(f"vertices={vertices.shape[0]}")
    print(f"triangles={tri_count}")
    print(f"file_size_bytes={size}")
    print(f"file_size_mb={size / (1024 * 1024):.2f}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
